package pl.webdevchallenge.meetmeuprest.event.util;

public enum SportsCategory {

    BADMINTON, BASEBALL, BILARD, BULE, CHEERLEADERING, CROSS_FIT, CURLING, DART, FRISBEE, GIMNASTYKA, GOCARTY, GOLF, HOKEJ, JEZDZIECTWO,
    KAJAKI, KITESURFING, KOLARSTWO, KOLARSTWO_MTB, KOSZYKOWKA, KREGLE, KRYKIET, KULTURYSTYKA, LEKKOATLETYKA, LYZWY, NARTY, NORDIC_WALKING, PAINTBALL,
    PILKA_NOZNA, PILKA_RECZNA, POKER, POLO, ROLKI, RUGBY, SIATKOWKA, SILOWNIA, SPORTY_PLAZOWE, SPORTY_WODNE, SPORTY_ZIMOWE, STRZELECTWO, SQUASH,
    SZACHY, SZTUKI_WALKI, TANIEC, TENIS, TENIS_STOLOWY, TRIATHLON, WARCABY, WSPINACZKA, ZEGLARSTWO

}
